### ISSUE TITLE
Completion in deoplete blocks when completing atoms

### ISSUE THREAD

**Issue by hahuang65** [archSeer/nvim-elixir#2]
As soon as I type `:` the entire editor blocks for about a minute.

I'm not sure if this is a deoplete issue, or an issue with this repo, or even with some way I may have misconfigured something. Have you seen anything like this before?

**Comment by jinyeow** [comment]
I changed `self.min_pattern_length` to 2. this stopped the blocking. on the other hand you have to press `<C-X><C-O>` to get the full omni-completion list for all erlang modules. It might not be the best workaround but it works for me so far.

**Comment by hahuang65** [comment]
This isn't settable right? I need to change the source?

**Comment by jinyeow** [comment]
No it's not settable. I had to change the source.

**Comment by hahuang65** [comment]
No longer care about this.
