### ISSUE TITLE
Failed to load elixir host. Maybe Erlang > 17.0 is missing

### ISSUE THREAD

**Issue by jfyne** [archSeer/nvim-elixir#4]
I've seen a previous issue with this error popping up but it was resolved, but I think there is a new issue:

On running `:UpdateRemotePlugins` is see this

```
function <SNR>45_UpdateRemotePlugins..<SNR>45_RegistrationCommands..remote#host#Require..<SNR>44_RequireElixirHost, line 8
Failed to load elixir host. Maybe Erlang > 17.0 is missing
```

After digging around a bit in the source I tried running `tools/nvim_elixir_host` which is what is failing for me:

```
$ ./tools/nvim_elixir_host

=INFO REPORT==== 10-Jul-2016::20:20:25 ===
    application: logger
    exited: {{shutdown,{failed_to_start_child,'Elixir.GenEvent',undef}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: temporary
Could not start application logger: Logger.App.start(:normal, []) returned an error: shutdown: failed to start child: GenEvent
    ** (EXIT) :undef
```

```
$ elixir -v
Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.1
```

I am not sure if this is the way to run it, but I believe this is what is causing the error. I will continue trying to figure out how to get it started

**Comment by archseer** [comment]
I'm sorry, but I currently offer no support for this, I'm currently running [Alchemist](http://www.alchemist-elixir.org/) + spacemacs; the code was readapted by awetzel back into one of his repos: https://github.com/awetzel/elixir.nvim
